language: go

matrix:
  include:
    - env: CHROME_CHANNEL=beta
      addons:
        chrome: beta
    - env: CHROME_CHANNEL=stable
      addons:
        chrome: stable

notifications:
  email:
    recipients:
      - paul@myitcv.io
    on_success: change
    on_failure: always

addons:
  chrome: beta

go:
  - 1.10.x

go_import_path: myitcv.io/react

before_script:
  - mkdir /tmp/google-chrome-bin && ln -s /usr/bin/google-chrome-$CHROME_CHANNEL /tmp/google-chrome-bin/google-chrome && export PATH=/tmp/google-chrome-bin:$PATH
  - curl -s https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip > /tmp/chromedriver_linux64.zip
  - unzip -d /tmp/chromedriver_linux64 /tmp/chromedriver_linux64.zip
  - export PATH=$PATH:/tmp/chromedriver_linux64

install: true

script:
  - ./_scripts/webpack_deps.sh
  - ./_scripts/run_tests.sh
  - ./_scripts/check_git_is_clean.sh
